version: '3.8'

services:
  fanpulse_api:
    image: 137568342949.dkr.ecr.us-east-1.amazonaws.com/fanpulse-app:latest
    container_name: fanpulse_api
    ports:
      - "80:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=${DB_CONNECTION}
      - Jwt__Key=${JWT_SECRET}
    restart: always
