import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "../_components/Header";
import Footer from "../_components/Footer";
import Auth from "../_components/Auth";
import QueryProvider from "@/providers/QueryProvider";
import { Suspense } from "react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fan Pulse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background">
         <Suspense fallback={<div>Loading...</div>}>
        <QueryProvider>
            <Header />
          <Auth />
          {children}
          <Footer />
        </QueryProvider>
       </Suspense>
      </body>

    </html>
  );
}
