import React, { Suspense } from "react";
import QueryProvider from "@/providers/QueryProvider";
import Header from "./_components/Header";
import Auth from "./_components/Auth";
import Footer from "./_components/Footer";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fan Pulse",
  description: "Generated by create next app",
};


export default function RootGlobalLayout({ children
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="uk">
            <body>
                <Suspense fallback={<div>Loading...</div>}>
                    <QueryProvider>
                        <Header />
                        <Auth />
                        {children}
                        <Footer />
                    </QueryProvider>
                </Suspense>
            </body>
        </html>
    );
}