/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthResponse,
  CategoryAddRequest,
  CategoryResponse,
  CategoryUpdateRequest,
  ChangePasswordRequest,
  CommentAddRequest,
  CommentReponse,
  GetApiCommentCommentsParams,
  GetApiCommentParams,
  GetApiLikeCheckParams,
  GetApiPostParams,
  GetApiReportUserReportsParams,
  LoginRequest,
  PostAddRequest,
  PostLike,
  PostResponce,
  ReportAddRequest,
  ReportResponse,
  UserAddRequest,
  UserResponse,
  UserUpdateRequest
} from './model';

import { customInstance } from './axios';




export const postApiAuthLogin = (
    loginRequest: LoginRequest,
 signal?: AbortSignal
) => {


      return customInstance<AuthResponse>(
      {url: `/api/Auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      );
    }



export const getPostApiAuthLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: LoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['postApiAuthLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthLogin>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthLogin(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthLogin>>>
    export type PostApiAuthLoginMutationBody = LoginRequest
    export type PostApiAuthLoginMutationError = unknown

    export const usePostApiAuthLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: LoginRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthLogin>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthLoginMutationOptions(options), queryClient);
    }

export const getApiCategory = (

 signal?: AbortSignal
) => {


      return customInstance<CategoryResponse[]>(
      {url: `/api/Category`, method: 'GET', signal
    },
      );
    }




export const getGetApiCategoryQueryKey = () => {
    return [
    `/api/Category`
    ] as const;
    }


export const getGetApiCategoryQueryOptions = <TData = Awaited<ReturnType<typeof getApiCategory>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategory>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCategoryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCategory>>> = ({ signal }) => getApiCategory(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCategory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCategoryQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCategory>>>
export type GetApiCategoryQueryError = unknown


export function useGetApiCategory<TData = Awaited<ReturnType<typeof getApiCategory>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategory>>,
          TError,
          Awaited<ReturnType<typeof getApiCategory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategory<TData = Awaited<ReturnType<typeof getApiCategory>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategory>>,
          TError,
          Awaited<ReturnType<typeof getApiCategory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategory<TData = Awaited<ReturnType<typeof getApiCategory>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategory>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCategory<TData = Awaited<ReturnType<typeof getApiCategory>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategory>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCategoryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const postApiCategory = (
    categoryAddRequest: CategoryAddRequest,
 signal?: AbortSignal
) => {


      return customInstance<CategoryResponse>(
      {url: `/api/Category`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: categoryAddRequest, signal
    },
      );
    }



export const getPostApiCategoryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCategory>>, TError,{data: CategoryAddRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiCategory>>, TError,{data: CategoryAddRequest}, TContext> => {

const mutationKey = ['postApiCategory'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCategory>>, {data: CategoryAddRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiCategory(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCategory>>>
    export type PostApiCategoryMutationBody = CategoryAddRequest
    export type PostApiCategoryMutationError = unknown

    export const usePostApiCategory = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCategory>>, TError,{data: CategoryAddRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCategory>>,
        TError,
        {data: CategoryAddRequest},
        TContext
      > => {
      return useMutation(getPostApiCategoryMutationOptions(options), queryClient);
    }

export const getApiCategoryRoots = (

 signal?: AbortSignal
) => {


      return customInstance<CategoryResponse[]>(
      {url: `/api/Category/roots`, method: 'GET', signal
    },
      );
    }




export const getGetApiCategoryRootsQueryKey = () => {
    return [
    `/api/Category/roots`
    ] as const;
    }


export const getGetApiCategoryRootsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCategoryRoots>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryRoots>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCategoryRootsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCategoryRoots>>> = ({ signal }) => getApiCategoryRoots(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryRoots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCategoryRootsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCategoryRoots>>>
export type GetApiCategoryRootsQueryError = unknown


export function useGetApiCategoryRoots<TData = Awaited<ReturnType<typeof getApiCategoryRoots>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryRoots>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryRoots>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryRoots>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryRoots<TData = Awaited<ReturnType<typeof getApiCategoryRoots>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryRoots>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryRoots>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryRoots>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryRoots<TData = Awaited<ReturnType<typeof getApiCategoryRoots>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryRoots>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCategoryRoots<TData = Awaited<ReturnType<typeof getApiCategoryRoots>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryRoots>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCategoryRootsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getApiCategoryId = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<CategoryResponse>(
      {url: `/api/Category/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetApiCategoryIdQueryKey = (id: string,) => {
    return [
    `/api/Category/${id}`
    ] as const;
    }


export const getGetApiCategoryIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCategoryId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCategoryIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCategoryId>>> = ({ signal }) => getApiCategoryId(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCategoryIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCategoryId>>>
export type GetApiCategoryIdQueryError = unknown


export function useGetApiCategoryId<TData = Awaited<ReturnType<typeof getApiCategoryId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryId>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryId<TData = Awaited<ReturnType<typeof getApiCategoryId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryId>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryId<TData = Awaited<ReturnType<typeof getApiCategoryId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCategoryId<TData = Awaited<ReturnType<typeof getApiCategoryId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCategoryIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const putApiCategoryId = (
    id: string,
    categoryUpdateRequest: CategoryUpdateRequest,
 signal?: AbortSignal
) => {


      return customInstance<CategoryResponse>(
      {url: `/api/Category/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: categoryUpdateRequest, signal
    },
      );
    }



export const getPutApiCategoryIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiCategoryId>>, TError,{id: string;data: CategoryUpdateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiCategoryId>>, TError,{id: string;data: CategoryUpdateRequest}, TContext> => {

const mutationKey = ['putApiCategoryId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiCategoryId>>, {id: string;data: CategoryUpdateRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiCategoryId(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiCategoryIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiCategoryId>>>
    export type PutApiCategoryIdMutationBody = CategoryUpdateRequest
    export type PutApiCategoryIdMutationError = unknown

    export const usePutApiCategoryId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiCategoryId>>, TError,{id: string;data: CategoryUpdateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiCategoryId>>,
        TError,
        {id: string;data: CategoryUpdateRequest},
        TContext
      > => {
      return useMutation(getPutApiCategoryIdMutationOptions(options), queryClient);
    }

export const deleteApiCategoryId = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Category/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteApiCategoryIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCategoryId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiCategoryId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiCategoryId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiCategoryId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiCategoryId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiCategoryIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiCategoryId>>>

    export type DeleteApiCategoryIdMutationError = unknown

    export const useDeleteApiCategoryId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCategoryId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiCategoryId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiCategoryIdMutationOptions(options), queryClient);
    }

export const getApiCategoryIdSubcategories = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<CategoryResponse[]>(
      {url: `/api/Category/${id}/subcategories`, method: 'GET', signal
    },
      );
    }




export const getGetApiCategoryIdSubcategoriesQueryKey = (id: string,) => {
    return [
    `/api/Category/${id}/subcategories`
    ] as const;
    }


export const getGetApiCategoryIdSubcategoriesQueryOptions = <TData = Awaited<ReturnType<typeof getApiCategoryIdSubcategories>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryIdSubcategories>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCategoryIdSubcategoriesQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCategoryIdSubcategories>>> = ({ signal }) => getApiCategoryIdSubcategories(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryIdSubcategories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCategoryIdSubcategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCategoryIdSubcategories>>>
export type GetApiCategoryIdSubcategoriesQueryError = unknown


export function useGetApiCategoryIdSubcategories<TData = Awaited<ReturnType<typeof getApiCategoryIdSubcategories>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryIdSubcategories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryIdSubcategories>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryIdSubcategories>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryIdSubcategories<TData = Awaited<ReturnType<typeof getApiCategoryIdSubcategories>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryIdSubcategories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCategoryIdSubcategories>>,
          TError,
          Awaited<ReturnType<typeof getApiCategoryIdSubcategories>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCategoryIdSubcategories<TData = Awaited<ReturnType<typeof getApiCategoryIdSubcategories>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryIdSubcategories>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCategoryIdSubcategories<TData = Awaited<ReturnType<typeof getApiCategoryIdSubcategories>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCategoryIdSubcategories>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCategoryIdSubcategoriesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getApiComment = (
    params?: GetApiCommentParams,
 signal?: AbortSignal
) => {


      return customInstance<CommentReponse[]>(
      {url: `/api/Comment`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetApiCommentQueryKey = (params?: GetApiCommentParams,) => {
    return [
    `/api/Comment`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiCommentQueryOptions = <TData = Awaited<ReturnType<typeof getApiComment>>, TError = unknown>(params?: GetApiCommentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiComment>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCommentQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiComment>>> = ({ signal }) => getApiComment(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiComment>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCommentQueryResult = NonNullable<Awaited<ReturnType<typeof getApiComment>>>
export type GetApiCommentQueryError = unknown


export function useGetApiComment<TData = Awaited<ReturnType<typeof getApiComment>>, TError = unknown>(
 params: undefined |  GetApiCommentParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiComment>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiComment>>,
          TError,
          Awaited<ReturnType<typeof getApiComment>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiComment<TData = Awaited<ReturnType<typeof getApiComment>>, TError = unknown>(
 params?: GetApiCommentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiComment>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiComment>>,
          TError,
          Awaited<ReturnType<typeof getApiComment>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiComment<TData = Awaited<ReturnType<typeof getApiComment>>, TError = unknown>(
 params?: GetApiCommentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiComment>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiComment<TData = Awaited<ReturnType<typeof getApiComment>>, TError = unknown>(
 params?: GetApiCommentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiComment>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCommentQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const postApiComment = (
    commentAddRequest: CommentAddRequest,
 signal?: AbortSignal
) => {


      return customInstance<CommentReponse>(
      {url: `/api/Comment`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: commentAddRequest, signal
    },
      );
    }



export const getPostApiCommentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiComment>>, TError,{data: CommentAddRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiComment>>, TError,{data: CommentAddRequest}, TContext> => {

const mutationKey = ['postApiComment'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiComment>>, {data: CommentAddRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiComment(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiCommentMutationResult = NonNullable<Awaited<ReturnType<typeof postApiComment>>>
    export type PostApiCommentMutationBody = CommentAddRequest
    export type PostApiCommentMutationError = unknown

    export const usePostApiComment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiComment>>, TError,{data: CommentAddRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiComment>>,
        TError,
        {data: CommentAddRequest},
        TContext
      > => {
      return useMutation(getPostApiCommentMutationOptions(options), queryClient);
    }

export const getApiCommentId = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<CommentReponse>(
      {url: `/api/Comment/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetApiCommentIdQueryKey = (id: string,) => {
    return [
    `/api/Comment/${id}`
    ] as const;
    }


export const getGetApiCommentIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCommentId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommentId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCommentIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCommentId>>> = ({ signal }) => getApiCommentId(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCommentId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCommentIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCommentId>>>
export type GetApiCommentIdQueryError = unknown


export function useGetApiCommentId<TData = Awaited<ReturnType<typeof getApiCommentId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommentId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCommentId>>,
          TError,
          Awaited<ReturnType<typeof getApiCommentId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCommentId<TData = Awaited<ReturnType<typeof getApiCommentId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommentId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCommentId>>,
          TError,
          Awaited<ReturnType<typeof getApiCommentId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCommentId<TData = Awaited<ReturnType<typeof getApiCommentId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommentId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCommentId<TData = Awaited<ReturnType<typeof getApiCommentId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommentId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCommentIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const putApiCommentId = (
    id: string,
    commentAddRequest: CommentAddRequest,
 signal?: AbortSignal
) => {


      return customInstance<CommentReponse>(
      {url: `/api/Comment/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: commentAddRequest, signal
    },
      );
    }



export const getPutApiCommentIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiCommentId>>, TError,{id: string;data: CommentAddRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiCommentId>>, TError,{id: string;data: CommentAddRequest}, TContext> => {

const mutationKey = ['putApiCommentId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiCommentId>>, {id: string;data: CommentAddRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiCommentId(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiCommentIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiCommentId>>>
    export type PutApiCommentIdMutationBody = CommentAddRequest
    export type PutApiCommentIdMutationError = unknown

    export const usePutApiCommentId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiCommentId>>, TError,{id: string;data: CommentAddRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiCommentId>>,
        TError,
        {id: string;data: CommentAddRequest},
        TContext
      > => {
      return useMutation(getPutApiCommentIdMutationOptions(options), queryClient);
    }

export const deleteApiCommentId = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<CommentReponse>(
      {url: `/api/Comment/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteApiCommentIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCommentId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiCommentId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiCommentId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiCommentId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiCommentId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiCommentIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiCommentId>>>

    export type DeleteApiCommentIdMutationError = unknown

    export const useDeleteApiCommentId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCommentId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiCommentId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiCommentIdMutationOptions(options), queryClient);
    }

export const getApiCommentIdChildrens = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<CommentReponse[]>(
      {url: `/api/Comment/${id}/childrens`, method: 'GET', signal
    },
      );
    }




export const getGetApiCommentIdChildrensQueryKey = (id: string,) => {
    return [
    `/api/Comment/${id}/childrens`
    ] as const;
    }


export const getGetApiCommentIdChildrensQueryOptions = <TData = Awaited<ReturnType<typeof getApiCommentIdChildrens>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommentIdChildrens>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCommentIdChildrensQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCommentIdChildrens>>> = ({ signal }) => getApiCommentIdChildrens(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCommentIdChildrens>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCommentIdChildrensQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCommentIdChildrens>>>
export type GetApiCommentIdChildrensQueryError = unknown


export function useGetApiCommentIdChildrens<TData = Awaited<ReturnType<typeof getApiCommentIdChildrens>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommentIdChildrens>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCommentIdChildrens>>,
          TError,
          Awaited<ReturnType<typeof getApiCommentIdChildrens>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCommentIdChildrens<TData = Awaited<ReturnType<typeof getApiCommentIdChildrens>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommentIdChildrens>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCommentIdChildrens>>,
          TError,
          Awaited<ReturnType<typeof getApiCommentIdChildrens>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCommentIdChildrens<TData = Awaited<ReturnType<typeof getApiCommentIdChildrens>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommentIdChildrens>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCommentIdChildrens<TData = Awaited<ReturnType<typeof getApiCommentIdChildrens>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommentIdChildrens>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCommentIdChildrensQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getApiCommentComments = (
    params?: GetApiCommentCommentsParams,
 signal?: AbortSignal
) => {


      return customInstance<CommentReponse[]>(
      {url: `/api/Comment/comments`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetApiCommentCommentsQueryKey = (params?: GetApiCommentCommentsParams,) => {
    return [
    `/api/Comment/comments`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiCommentCommentsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCommentComments>>, TError = unknown>(params?: GetApiCommentCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommentComments>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCommentCommentsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCommentComments>>> = ({ signal }) => getApiCommentComments(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCommentComments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCommentCommentsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCommentComments>>>
export type GetApiCommentCommentsQueryError = unknown


export function useGetApiCommentComments<TData = Awaited<ReturnType<typeof getApiCommentComments>>, TError = unknown>(
 params: undefined |  GetApiCommentCommentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommentComments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCommentComments>>,
          TError,
          Awaited<ReturnType<typeof getApiCommentComments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCommentComments<TData = Awaited<ReturnType<typeof getApiCommentComments>>, TError = unknown>(
 params?: GetApiCommentCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommentComments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCommentComments>>,
          TError,
          Awaited<ReturnType<typeof getApiCommentComments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCommentComments<TData = Awaited<ReturnType<typeof getApiCommentComments>>, TError = unknown>(
 params?: GetApiCommentCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommentComments>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiCommentComments<TData = Awaited<ReturnType<typeof getApiCommentComments>>, TError = unknown>(
 params?: GetApiCommentCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommentComments>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCommentCommentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getApiLikeCountTargetId = (
    targetId: string,
 signal?: AbortSignal
) => {


      return customInstance<number>(
      {url: `/api/Like/count/${targetId}`, method: 'GET', signal
    },
      );
    }




export const getGetApiLikeCountTargetIdQueryKey = (targetId: string,) => {
    return [
    `/api/Like/count/${targetId}`
    ] as const;
    }


export const getGetApiLikeCountTargetIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiLikeCountTargetId>>, TError = unknown>(targetId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLikeCountTargetId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLikeCountTargetIdQueryKey(targetId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLikeCountTargetId>>> = ({ signal }) => getApiLikeCountTargetId(targetId, signal);





   return  { queryKey, queryFn, enabled: !!(targetId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiLikeCountTargetId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLikeCountTargetIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLikeCountTargetId>>>
export type GetApiLikeCountTargetIdQueryError = unknown


export function useGetApiLikeCountTargetId<TData = Awaited<ReturnType<typeof getApiLikeCountTargetId>>, TError = unknown>(
 targetId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLikeCountTargetId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLikeCountTargetId>>,
          TError,
          Awaited<ReturnType<typeof getApiLikeCountTargetId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLikeCountTargetId<TData = Awaited<ReturnType<typeof getApiLikeCountTargetId>>, TError = unknown>(
 targetId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLikeCountTargetId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLikeCountTargetId>>,
          TError,
          Awaited<ReturnType<typeof getApiLikeCountTargetId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLikeCountTargetId<TData = Awaited<ReturnType<typeof getApiLikeCountTargetId>>, TError = unknown>(
 targetId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLikeCountTargetId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiLikeCountTargetId<TData = Awaited<ReturnType<typeof getApiLikeCountTargetId>>, TError = unknown>(
 targetId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLikeCountTargetId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLikeCountTargetIdQueryOptions(targetId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getApiLikeCheck = (
    params?: GetApiLikeCheckParams,
 signal?: AbortSignal
) => {


      return customInstance<boolean>(
      {url: `/api/Like/check`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetApiLikeCheckQueryKey = (params?: GetApiLikeCheckParams,) => {
    return [
    `/api/Like/check`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiLikeCheckQueryOptions = <TData = Awaited<ReturnType<typeof getApiLikeCheck>>, TError = unknown>(params?: GetApiLikeCheckParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLikeCheck>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLikeCheckQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLikeCheck>>> = ({ signal }) => getApiLikeCheck(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiLikeCheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLikeCheckQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLikeCheck>>>
export type GetApiLikeCheckQueryError = unknown


export function useGetApiLikeCheck<TData = Awaited<ReturnType<typeof getApiLikeCheck>>, TError = unknown>(
 params: undefined |  GetApiLikeCheckParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLikeCheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLikeCheck>>,
          TError,
          Awaited<ReturnType<typeof getApiLikeCheck>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLikeCheck<TData = Awaited<ReturnType<typeof getApiLikeCheck>>, TError = unknown>(
 params?: GetApiLikeCheckParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLikeCheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLikeCheck>>,
          TError,
          Awaited<ReturnType<typeof getApiLikeCheck>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLikeCheck<TData = Awaited<ReturnType<typeof getApiLikeCheck>>, TError = unknown>(
 params?: GetApiLikeCheckParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLikeCheck>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiLikeCheck<TData = Awaited<ReturnType<typeof getApiLikeCheck>>, TError = unknown>(
 params?: GetApiLikeCheckParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLikeCheck>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLikeCheckQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const postApiLike = (
    postLike: PostLike,
 signal?: AbortSignal
) => {


      return customInstance<PostLike>(
      {url: `/api/Like`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postLike, signal
    },
      );
    }



export const getPostApiLikeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLike>>, TError,{data: PostLike}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiLike>>, TError,{data: PostLike}, TContext> => {

const mutationKey = ['postApiLike'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiLike>>, {data: PostLike}> = (props) => {
          const {data} = props ?? {};

          return  postApiLike(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiLikeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiLike>>>
    export type PostApiLikeMutationBody = PostLike
    export type PostApiLikeMutationError = unknown

    export const usePostApiLike = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLike>>, TError,{data: PostLike}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiLike>>,
        TError,
        {data: PostLike},
        TContext
      > => {
      return useMutation(getPostApiLikeMutationOptions(options), queryClient);
    }

export const deleteApiLikeId = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Like/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteApiLikeIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiLikeId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiLikeId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiLikeId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiLikeId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiLikeId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiLikeIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiLikeId>>>

    export type DeleteApiLikeIdMutationError = unknown

    export const useDeleteApiLikeId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiLikeId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiLikeId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiLikeIdMutationOptions(options), queryClient);
    }

export const getApiPost = (
    params?: GetApiPostParams,
 signal?: AbortSignal
) => {


      return customInstance<PostResponce[]>(
      {url: `/api/Post`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetApiPostQueryKey = (params?: GetApiPostParams,) => {
    return [
    `/api/Post`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiPostQueryOptions = <TData = Awaited<ReturnType<typeof getApiPost>>, TError = unknown>(params?: GetApiPostParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPost>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPostQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPost>>> = ({ signal }) => getApiPost(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPostQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPost>>>
export type GetApiPostQueryError = unknown


export function useGetApiPost<TData = Awaited<ReturnType<typeof getApiPost>>, TError = unknown>(
 params: undefined |  GetApiPostParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPost>>,
          TError,
          Awaited<ReturnType<typeof getApiPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPost<TData = Awaited<ReturnType<typeof getApiPost>>, TError = unknown>(
 params?: GetApiPostParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPost>>,
          TError,
          Awaited<ReturnType<typeof getApiPost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPost<TData = Awaited<ReturnType<typeof getApiPost>>, TError = unknown>(
 params?: GetApiPostParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPost>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPost<TData = Awaited<ReturnType<typeof getApiPost>>, TError = unknown>(
 params?: GetApiPostParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPost>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPostQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const postApiPost = (
    postAddRequest: PostAddRequest,
 signal?: AbortSignal
) => {


      return customInstance<PostResponce>(
      {url: `/api/Post`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAddRequest, signal
    },
      );
    }



export const getPostApiPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPost>>, TError,{data: PostAddRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiPost>>, TError,{data: PostAddRequest}, TContext> => {

const mutationKey = ['postApiPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiPost>>, {data: PostAddRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiPostMutationResult = NonNullable<Awaited<ReturnType<typeof postApiPost>>>
    export type PostApiPostMutationBody = PostAddRequest
    export type PostApiPostMutationError = unknown

    export const usePostApiPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPost>>, TError,{data: PostAddRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiPost>>,
        TError,
        {data: PostAddRequest},
        TContext
      > => {
      return useMutation(getPostApiPostMutationOptions(options), queryClient);
    }

export const getApiPostId = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<PostResponce>(
      {url: `/api/Post/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetApiPostIdQueryKey = (id: string,) => {
    return [
    `/api/Post/${id}`
    ] as const;
    }


export const getGetApiPostIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiPostId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPostId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPostIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPostId>>> = ({ signal }) => getApiPostId(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPostId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPostIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPostId>>>
export type GetApiPostIdQueryError = unknown


export function useGetApiPostId<TData = Awaited<ReturnType<typeof getApiPostId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPostId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPostId>>,
          TError,
          Awaited<ReturnType<typeof getApiPostId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPostId<TData = Awaited<ReturnType<typeof getApiPostId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPostId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPostId>>,
          TError,
          Awaited<ReturnType<typeof getApiPostId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPostId<TData = Awaited<ReturnType<typeof getApiPostId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPostId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPostId<TData = Awaited<ReturnType<typeof getApiPostId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPostId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPostIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const putApiPostId = (
    id: string,
    postAddRequest: PostAddRequest,
 signal?: AbortSignal
) => {


      return customInstance<PostResponce>(
      {url: `/api/Post/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: postAddRequest, signal
    },
      );
    }



export const getPutApiPostIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiPostId>>, TError,{id: string;data: PostAddRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiPostId>>, TError,{id: string;data: PostAddRequest}, TContext> => {

const mutationKey = ['putApiPostId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiPostId>>, {id: string;data: PostAddRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiPostId(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiPostIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiPostId>>>
    export type PutApiPostIdMutationBody = PostAddRequest
    export type PutApiPostIdMutationError = unknown

    export const usePutApiPostId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiPostId>>, TError,{id: string;data: PostAddRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiPostId>>,
        TError,
        {id: string;data: PostAddRequest},
        TContext
      > => {
      return useMutation(getPutApiPostIdMutationOptions(options), queryClient);
    }

export const deleteApiPostId = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Post/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteApiPostIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiPostId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiPostId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiPostId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiPostId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiPostId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiPostIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiPostId>>>

    export type DeleteApiPostIdMutationError = unknown

    export const useDeleteApiPostId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiPostId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiPostId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiPostIdMutationOptions(options), queryClient);
    }

export const getApiReportId = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<ReportResponse>(
      {url: `/api/Report/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetApiReportIdQueryKey = (id: string,) => {
    return [
    `/api/Report/${id}`
    ] as const;
    }


export const getGetApiReportIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiReportId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReportId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiReportIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiReportId>>> = ({ signal }) => getApiReportId(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiReportId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiReportIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiReportId>>>
export type GetApiReportIdQueryError = unknown


export function useGetApiReportId<TData = Awaited<ReturnType<typeof getApiReportId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReportId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReportId>>,
          TError,
          Awaited<ReturnType<typeof getApiReportId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReportId<TData = Awaited<ReturnType<typeof getApiReportId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReportId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReportId>>,
          TError,
          Awaited<ReturnType<typeof getApiReportId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReportId<TData = Awaited<ReturnType<typeof getApiReportId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReportId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiReportId<TData = Awaited<ReturnType<typeof getApiReportId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReportId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiReportIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const putApiReportId = (
    id: string,
    reportAddRequest: ReportAddRequest,
 signal?: AbortSignal
) => {


      return customInstance<ReportResponse>(
      {url: `/api/Report/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: reportAddRequest, signal
    },
      );
    }



export const getPutApiReportIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiReportId>>, TError,{id: string;data: ReportAddRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiReportId>>, TError,{id: string;data: ReportAddRequest}, TContext> => {

const mutationKey = ['putApiReportId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiReportId>>, {id: string;data: ReportAddRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiReportId(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiReportIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiReportId>>>
    export type PutApiReportIdMutationBody = ReportAddRequest
    export type PutApiReportIdMutationError = unknown

    export const usePutApiReportId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiReportId>>, TError,{id: string;data: ReportAddRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiReportId>>,
        TError,
        {id: string;data: ReportAddRequest},
        TContext
      > => {
      return useMutation(getPutApiReportIdMutationOptions(options), queryClient);
    }

export const deleteApiReportId = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Report/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteApiReportIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiReportId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiReportId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiReportId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiReportId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiReportId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiReportIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiReportId>>>

    export type DeleteApiReportIdMutationError = unknown

    export const useDeleteApiReportId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiReportId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiReportId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiReportIdMutationOptions(options), queryClient);
    }

export const postApiReport = (
    reportAddRequest: ReportAddRequest,
 signal?: AbortSignal
) => {


      return customInstance<ReportResponse>(
      {url: `/api/Report`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reportAddRequest, signal
    },
      );
    }



export const getPostApiReportMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiReport>>, TError,{data: ReportAddRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiReport>>, TError,{data: ReportAddRequest}, TContext> => {

const mutationKey = ['postApiReport'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiReport>>, {data: ReportAddRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiReport(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiReportMutationResult = NonNullable<Awaited<ReturnType<typeof postApiReport>>>
    export type PostApiReportMutationBody = ReportAddRequest
    export type PostApiReportMutationError = unknown

    export const usePostApiReport = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiReport>>, TError,{data: ReportAddRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiReport>>,
        TError,
        {data: ReportAddRequest},
        TContext
      > => {
      return useMutation(getPostApiReportMutationOptions(options), queryClient);
    }

export const getApiReportUserReports = (
    params?: GetApiReportUserReportsParams,
 signal?: AbortSignal
) => {


      return customInstance<ReportResponse[]>(
      {url: `/api/Report/user-reports`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetApiReportUserReportsQueryKey = (params?: GetApiReportUserReportsParams,) => {
    return [
    `/api/Report/user-reports`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiReportUserReportsQueryOptions = <TData = Awaited<ReturnType<typeof getApiReportUserReports>>, TError = unknown>(params?: GetApiReportUserReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReportUserReports>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiReportUserReportsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiReportUserReports>>> = ({ signal }) => getApiReportUserReports(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiReportUserReports>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiReportUserReportsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiReportUserReports>>>
export type GetApiReportUserReportsQueryError = unknown


export function useGetApiReportUserReports<TData = Awaited<ReturnType<typeof getApiReportUserReports>>, TError = unknown>(
 params: undefined |  GetApiReportUserReportsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReportUserReports>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReportUserReports>>,
          TError,
          Awaited<ReturnType<typeof getApiReportUserReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReportUserReports<TData = Awaited<ReturnType<typeof getApiReportUserReports>>, TError = unknown>(
 params?: GetApiReportUserReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReportUserReports>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReportUserReports>>,
          TError,
          Awaited<ReturnType<typeof getApiReportUserReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReportUserReports<TData = Awaited<ReturnType<typeof getApiReportUserReports>>, TError = unknown>(
 params?: GetApiReportUserReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReportUserReports>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiReportUserReports<TData = Awaited<ReturnType<typeof getApiReportUserReports>>, TError = unknown>(
 params?: GetApiReportUserReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReportUserReports>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiReportUserReportsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const patchApiReportIdClose = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<ReportResponse>(
      {url: `/api/Report/${id}/close`, method: 'PATCH', signal
    },
      );
    }



export const getPatchApiReportIdCloseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiReportIdClose>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiReportIdClose>>, TError,{id: string}, TContext> => {

const mutationKey = ['patchApiReportIdClose'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiReportIdClose>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  patchApiReportIdClose(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiReportIdCloseMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiReportIdClose>>>

    export type PatchApiReportIdCloseMutationError = unknown

    export const usePatchApiReportIdClose = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiReportIdClose>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiReportIdClose>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPatchApiReportIdCloseMutationOptions(options), queryClient);
    }

export const getApiUser = (

 signal?: AbortSignal
) => {


      return customInstance<UserResponse[]>(
      {url: `/api/User`, method: 'GET', signal
    },
      );
    }




export const getGetApiUserQueryKey = () => {
    return [
    `/api/User`
    ] as const;
    }


export const getGetApiUserQueryOptions = <TData = Awaited<ReturnType<typeof getApiUser>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUser>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiUserQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUser>>> = ({ signal }) => getApiUser(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiUserQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUser>>>
export type GetApiUserQueryError = unknown


export function useGetApiUser<TData = Awaited<ReturnType<typeof getApiUser>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUser>>,
          TError,
          Awaited<ReturnType<typeof getApiUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUser<TData = Awaited<ReturnType<typeof getApiUser>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUser>>,
          TError,
          Awaited<ReturnType<typeof getApiUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUser<TData = Awaited<ReturnType<typeof getApiUser>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUser>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiUser<TData = Awaited<ReturnType<typeof getApiUser>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUser>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiUserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const postApiUser = (
    userAddRequest: UserAddRequest,
 signal?: AbortSignal
) => {


      return customInstance<UserResponse>(
      {url: `/api/User`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userAddRequest, signal
    },
      );
    }



export const getPostApiUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUser>>, TError,{data: UserAddRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiUser>>, TError,{data: UserAddRequest}, TContext> => {

const mutationKey = ['postApiUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiUser>>, {data: UserAddRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiUser(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiUserMutationResult = NonNullable<Awaited<ReturnType<typeof postApiUser>>>
    export type PostApiUserMutationBody = UserAddRequest
    export type PostApiUserMutationError = unknown

    export const usePostApiUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUser>>, TError,{data: UserAddRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiUser>>,
        TError,
        {data: UserAddRequest},
        TContext
      > => {
      return useMutation(getPostApiUserMutationOptions(options), queryClient);
    }

export const getMe = (

 signal?: AbortSignal
) => {


      return customInstance<UserResponse>(
      {url: `/me`, method: 'GET', signal
    },
      );
    }




export const getGetMeQueryKey = () => {
    return [
    `/me`
    ] as const;
    }


export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = unknown


export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getApiUserId = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<UserResponse>(
      {url: `/api/User/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetApiUserIdQueryKey = (id: string,) => {
    return [
    `/api/User/${id}`
    ] as const;
    }


export const getGetApiUserIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiUserId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiUserIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUserId>>> = ({ signal }) => getApiUserId(id, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiUserId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiUserIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUserId>>>
export type GetApiUserIdQueryError = unknown


export function useGetApiUserId<TData = Awaited<ReturnType<typeof getApiUserId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUserId>>,
          TError,
          Awaited<ReturnType<typeof getApiUserId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUserId<TData = Awaited<ReturnType<typeof getApiUserId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUserId>>,
          TError,
          Awaited<ReturnType<typeof getApiUserId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUserId<TData = Awaited<ReturnType<typeof getApiUserId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiUserId<TData = Awaited<ReturnType<typeof getApiUserId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUserId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiUserIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const putApiUserId = (
    id: string,
    userUpdateRequest: UserUpdateRequest,
 signal?: AbortSignal
) => {


      return customInstance<UserResponse>(
      {url: `/api/User/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: userUpdateRequest, signal
    },
      );
    }



export const getPutApiUserIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiUserId>>, TError,{id: string;data: UserUpdateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiUserId>>, TError,{id: string;data: UserUpdateRequest}, TContext> => {

const mutationKey = ['putApiUserId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiUserId>>, {id: string;data: UserUpdateRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiUserId(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiUserIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiUserId>>>
    export type PutApiUserIdMutationBody = UserUpdateRequest
    export type PutApiUserIdMutationError = unknown

    export const usePutApiUserId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiUserId>>, TError,{id: string;data: UserUpdateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiUserId>>,
        TError,
        {id: string;data: UserUpdateRequest},
        TContext
      > => {
      return useMutation(getPutApiUserIdMutationOptions(options), queryClient);
    }

export const deleteApiUserId = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<UserResponse>(
      {url: `/api/User/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteApiUserIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiUserId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiUserId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiUserId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiUserId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiUserId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiUserIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiUserId>>>

    export type DeleteApiUserIdMutationError = unknown

    export const useDeleteApiUserId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiUserId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiUserId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiUserIdMutationOptions(options), queryClient);
    }

export const patchApiUserIdChangePassword = (
    id: string,
    changePasswordRequest: ChangePasswordRequest,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/User/${id}/change-password`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordRequest, signal
    },
      );
    }



export const getPatchApiUserIdChangePasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiUserIdChangePassword>>, TError,{id: string;data: ChangePasswordRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiUserIdChangePassword>>, TError,{id: string;data: ChangePasswordRequest}, TContext> => {

const mutationKey = ['patchApiUserIdChangePassword'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiUserIdChangePassword>>, {id: string;data: ChangePasswordRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiUserIdChangePassword(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiUserIdChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiUserIdChangePassword>>>
    export type PatchApiUserIdChangePasswordMutationBody = ChangePasswordRequest
    export type PatchApiUserIdChangePasswordMutationError = unknown

    export const usePatchApiUserIdChangePassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiUserIdChangePassword>>, TError,{id: string;data: ChangePasswordRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiUserIdChangePassword>>,
        TError,
        {id: string;data: ChangePasswordRequest},
        TContext
      > => {
      return useMutation(getPatchApiUserIdChangePasswordMutationOptions(options), queryClient);
    }

