/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */

export interface AuthResponse {
  /** @nullable */
  token?: string | null;
  /** @nullable */
  email?: string | null;
  userId?: string;
}
