/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */

export interface CategoryUpdateRequest {
  /**
     * @minLength 2
     * @maxLength 100
     * @nullable
     */
  name?: string | null;
  /** @nullable */
  parentId?: string | null;
}
