/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */
import type { Category as __Category } from './category';
import type { User } from './user';

export interface Category {
  id?: string;
  /** @nullable */
  parentId?: string | null;
  parent?: __Category;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  children?: Category[] | null;
  /** @nullable */
  users?: User[] | null;
}
