/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */

export interface ChangePasswordRequest {
  /** @nullable */
  currentPassword?: string | null;
  /** @nullable */
  newPassword?: string | null;
}
