/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */
import type { CommentReponse as __CommentReponse } from './commentReponse';
import type { PostResponce } from './postResponce';
import type { UserResponse } from './userResponse';

export interface CommentReponse {
  id?: string;
  post?: PostResponce;
  /** @minLength 1 */
  commentText: string;
  parent?: __CommentReponse;
  /** @nullable */
  children?: CommentReponse[] | null;
  user?: UserResponse;
}
