/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */

export interface CommentAddRequest {
  /** @minLength 1 */
  commentText: string;
  postId: string;
  /** @nullable */
  parrentId?: string | null;
}
