/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */
import type { Comment as __Comment } from './comment';
import type { Post } from './post';
import type { User } from './user';

export interface Comment {
  id?: string;
  /** @nullable */
  postId?: string | null;
  post?: Post;
  /** @minLength 1 */
  commentText: string;
  /** @nullable */
  parentId?: string | null;
  parent?: __Comment;
  /** @nullable */
  children?: Comment[] | null;
  userId?: string;
  user?: User;
  createdAt?: string;
  updatedAt?: string;
}
