/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */
import type { CategoryResponse } from './categoryResponse';
import type { Comment } from './comment';
import type { PostLike } from './postLike';
import type { UserResponse } from './userResponse';

export interface PostResponce {
  id?: string;
  /** @minLength 1 */
  title: string;
  /** @minLength 1 */
  description: string;
  userId?: string;
  user?: UserResponse;
  category?: CategoryResponse;
  /** @nullable */
  likes?: PostLike[] | null;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  comments?: Comment[] | null;
}
