/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */

export interface PostAddRequest {
  /** @minLength 1 */
  title: string;
  /** @minLength 1 */
  description: string;
  categoryId: string;
}
