/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */
import type { Post } from './post';
import type { User } from './user';

export interface PostLike {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  postId?: string | null;
  /** @nullable */
  commentId?: string | null;
  post?: Post;
  user?: User;
  createdAt?: string;
  updatedAt?: string;
}
