/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */
import type { Category } from './category';
import type { Comment } from './comment';
import type { PostLike } from './postLike';
import type { User } from './user';

export interface Post {
  id?: string;
  /** @minLength 1 */
  title: string;
  /** @minLength 1 */
  description: string;
  userId?: string;
  user?: User;
  /** @nullable */
  categoryId?: string | null;
  category?: Category;
  /** @nullable */
  likes?: PostLike[] | null;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  comments?: Comment[] | null;
}
