/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */
import type { ReportReasons } from './reportReasons';

export interface ReportAddRequest {
  reportedId?: string;
  /** @nullable */
  description?: string | null;
  reason?: ReportReasons;
}
