/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */
import type { ReportReasons } from './reportReasons';
import type { ReportStatus } from './reportStatus';
import type { UserResponse } from './userResponse';

export interface ReportResponse {
  id?: string;
  reportedUser?: UserResponse;
  reporter?: UserResponse;
  /** @nullable */
  description?: string | null;
  status?: ReportStatus;
  reason?: ReportReasons;
  createdAt?: string;
  updatedAt?: string;
}
