/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */

export interface UserUpdateRequest {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
}
