/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */
import type { UserActivityDto } from './userActivityDto';

export interface UserResponse {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  isVerifiedUser?: boolean;
  createdAt?: string;
  /** @nullable */
  countOfPosts?: number | null;
  /** @nullable */
  countOfComments?: number | null;
  /** @nullable */
  countOfLkes?: number | null;
  /** @nullable */
  recentActivities?: UserActivityDto[] | null;
}
