/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */
import type { Category } from './category';
import type { Comment } from './comment';
import type { Post } from './post';
import type { PostLike } from './postLike';

export interface User {
  id?: string;
  /** @nullable */
  roleId?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  /** @nullable */
  passwordHash?: string | null;
  /** @nullable */
  passwordSalt?: string | null;
  isVerifiedUser?: boolean;
  isEmailVerified?: boolean;
  isDeleted?: boolean;
  isBanned?: boolean;
  banCount?: number;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  updatedBy?: string | null;
  /** @nullable */
  favCategories?: Category[] | null;
  /** @nullable */
  posts?: Post[] | null;
  /** @nullable */
  likes?: PostLike[] | null;
  /** @nullable */
  comments?: Comment[] | null;
}
