/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FanPulseApi
 * OpenAPI spec version: 1.0
 */

export interface UserAddRequest {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  /** @nullable */
  favCategoryIds?: string[] | null;
}
